apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Travel-Blog
  region: us-east-1

nodeGroups:
  - name: Travel-Blog-NG-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      allow: false # will use ~/.ssh/id_rsa.pub as the default ssh key
    
