version: 2
jobs:
   build:
    environment:
      IMAGE_NAME: danielsiefert/devops-capstone
    docker:
      - image: circleci/buildpack-deps:strech
    steps:
    - checkout
    - setup_remote_docker
    - run:
         name: Build Docker image
         command: |
           docker build -t $IMAGE_NAME:latest .
           docker image ls
workflows:
 version: 2
 build-master:
   jobs:
     - build:
         filters:
           branches:
             only: CI   